language: node_js

sudo: false

node_js:
  - "6"

script:
  - npm run eslint
  - npm run test-cov

notifications:
  email:
    recipients:
      - chenshuai92@hotmail.com 
    on_success: change
    on_failure: change
